print('from email.message import EmailMessage')
print('import ssl')
print('import smtplib')
print('')
print('email_sender = "YOUR EMAIL"')
print('email_password = "YORE PASSWORD"')
print('email_receiver = "TO ?",email_sender')
print('')
print('subject = "hallo"')
print('body = """')
print('hello !')
print('')
print('I LOVE YOU')
print('"""')
print('')
print('')
print('em = EmailMessage()')
print('em["From"] = email_sender')
print('em["To"] = email_receiver')
print('em["Subject"] = subject')
print('em.set_content(body)')
print('')
print('')
print('with open("PATH FILE", "rb") as f:')
print('file_data = f.read()')
print('em.add_attachment(file_data, maintype="application", subtype="FILE TYPE", filename="FILE NAME")')
print('')
print('context = ssl.create_default_context()')
print('')
print('with smtplib.SMTP_SSL("smtp.gmail.com",465,context=context) as smtp:')
print('smtp.login(email_sender,email_password)')
print('smtp.sendmail(email_sender,email_receiver,em.as_string())')